# Generated by Django 5.0.7 on 2024-08-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='idrol',
            new_name='rol',
        ),
    ]
