# Generated by Django 5.0.7 on 2024-08-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_idrol_rol_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='rol',
        ),
    ]
