# Generated by Django 5.0.7 on 2024-08-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_rol_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='Nrol',
            field=models.IntegerField(default=1),
        ),
    ]
