# Generated by Django 5.0.7 on 2024-08-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fecha_sesion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
