# Generated by Django 5.0.7 on 2024-08-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_fecha_sesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='Nrol',
        ),
    ]
