# Generated by Django 5.0.7 on 2024-08-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userprofile_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.CharField(blank=True, default='Usuario normal con permisos limitados', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombrerol',
            field=models.CharField(blank=True, default='User', max_length=20, null=True),
        ),
    ]
