# Generated by Django 5.0.7 on 2024-08-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_rol_descripcion_alter_rol_nombrerol'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codigo_verificacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
