# Generated by Django 5.1.1 on 2025-06-20 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprofile_user_alter_userprofile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreTela', models.CharField(max_length=45)),
                ('TipoTela', models.CharField(max_length=45)),
                ('PrecioTela', models.BigIntegerField()),
                ('fecha_agregado', models.DateField()),
                ('Disponibilidad', models.CharField(max_length=45)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.rol'),
        ),
    ]
