# Generated by Django 5.1.1 on 2025-06-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tela_alter_userprofile_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('IdColor', models.BigAutoField(primary_key=True, serialize=False)),
                ('NombreColor', models.CharField(max_length=45)),
                ('disponibilidad', models.CharField(max_length=2)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estampado',
            fields=[
                ('idEstampado', models.BigAutoField(primary_key=True, serialize=False)),
                ('NombreEstampado', models.CharField(max_length=45)),
                ('TipoEstampado', models.CharField(max_length=45)),
                ('PrecioEstampado', models.BigIntegerField()),
                ('ImgEstampado', models.CharField(max_length=100)),
                ('ColorEstampado', models.CharField(max_length=45)),
                ('fecha_agregado', models.DateField()),
                ('Disponibilidad', models.CharField(max_length=45)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'estampado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProductos', models.BigAutoField(primary_key=True, serialize=False)),
                ('NombreProductos', models.CharField(max_length=45)),
                ('imgProducto', models.CharField(max_length=100)),
                ('TipoProductos', models.CharField(max_length=45)),
                ('PrecioProducto', models.BigIntegerField()),
                ('Descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField()),
                ('fecha_actualizacion', models.DateField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('idTallas', models.BigAutoField(primary_key=True, serialize=False)),
                ('Talla', models.CharField(max_length=3)),
                ('Disponibilidad', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=45)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tallas',
            },
        ),
        migrations.AlterModelOptions(
            name='tela',
            options={'managed': False},
        ),
    ]
