# Generated by Django 5.0.7 on 2025-10-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tela_alter_userprofile_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estampado',
            fields=[
                ('idEstampado', models.BigAutoField(primary_key=True, serialize=False)),
                ('NombreEstampado', models.CharField(max_length=45)),
                ('TipoEstampado', models.CharField(max_length=45)),
                ('ImgEstampado', models.CharField(max_length=100)),
                ('ColorEstampado', models.CharField(max_length=45)),
                ('fecha_agregado', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('PrecioEstampado', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estampado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProductos', models.BigAutoField(primary_key=True, serialize=False)),
                ('NombreProductos', models.CharField(max_length=45)),
                ('TipoProductos', models.CharField(max_length=45)),
                ('PrecioProducto', models.BigIntegerField()),
                ('Descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('urlFrontal', models.CharField(blank=True, max_length=100, null=True)),
                ('urlEspaldar', models.CharField(blank=True, max_length=100, null=True)),
                ('urlMangaIzquierda', models.CharField(blank=True, max_length=100, null=True)),
                ('urlMangaDerecha', models.CharField(blank=True, max_length=100, null=True)),
                ('Tallas', models.CharField(max_length=50)),
                ('Color', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosPersonalizados',
            fields=[
                ('idProductosPeronalizaos', models.BigAutoField(db_column='idProductosPeronalizaos', primary_key=True, serialize=False)),
                ('NombrePersonalizado', models.CharField(blank=True, db_column='NombrePersonalizado', max_length=45, null=True)),
                ('precioPersonalizado', models.FloatField(blank=True, db_column='precioPersonalizado', null=True)),
                ('rolProducto', models.CharField(blank=True, db_column='rolProducto', max_length=45, null=True)),
                ('stock', models.IntegerField(db_column='stock', default=0)),
                ('urlFrontal', models.CharField(blank=True, db_column='urlFrontal', max_length=100, null=True)),
                ('urlEspadarl', models.CharField(blank=True, db_column='urlEspadarl', max_length=100, null=True)),
                ('urlMangaDerecha', models.CharField(blank=True, db_column='urlMangaDerecha', max_length=100, null=True)),
                ('urlMangaIzquierda', models.CharField(blank=True, db_column='urlMangaIzquierda', max_length=100, null=True)),
            ],
            options={
                'db_table': 'productosperonalizaos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosPersonalizadosHasEstampado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'productosperonalizaos_has_estampado',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tela',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='ProveedorSolicitud',
            fields=[
                ('id_solicitud', models.AutoField(db_column='id_solicitud', primary_key=True, serialize=False)),
                ('nit_cedula', models.CharField(db_column='Nitcedula', max_length=30)),
                ('direccion', models.CharField(max_length=255)),
                ('nombre_empresa', models.CharField(db_column='NombreEmpresa', max_length=255)),
                ('descripcion_empresa', models.TextField(db_column='descripcionEmpresa')),
                ('anios_experiencia', models.IntegerField(db_column='AñosExp')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado')], db_column='Estado', default='Pendiente', max_length=20)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proveedorsolicitud',
            },
        ),
    ]
