# Generated by Django 5.1.1 on 2025-10-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_estampado_producto_productospersonalizados_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tela',
            table='tela',
        ),
    ]
