# Generated by Django 5.1.6 on 2025-06-27 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_color_estampado_producto_proveedor_talla_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tela',
            table='tela',
        ),
    ]
