# Generated by Django 5.1.6 on 2025-08-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_tela_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorSolicitud',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('nit_cedula', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=255)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('descripcion_empresa', models.TextField()),
                ('anios_experiencia', models.IntegerField()),
                ('estado', models.CharField(blank=True, default='Pendiente', max_length=20, null=True)),
                ('id_us', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'proveedorsolicitud',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
