# Generated by Django 5.2.2 on 2025-11-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_tela_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={},
        ),
    ]
