# Generated by Django 5.2.2 on 2025-11-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_producto_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
