# Generated by Django 5.1.6 on 2025-08-18 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_proveedorsolicitud_delete_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedorsolicitud',
            options={},
        ),
    ]
