# Generated by Django 5.1.6 on 2025-08-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_proveedorsolicitud_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedorsolicitud',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='proveedorsolicitud',
            name='id_us',
        ),
        migrations.AlterField(
            model_name='proveedorsolicitud',
            name='anios_experiencia',
            field=models.IntegerField(db_column='AñosExp'),
        ),
        migrations.AlterField(
            model_name='proveedorsolicitud',
            name='descripcion_empresa',
            field=models.TextField(db_column='descripcionEmpresa'),
        ),
        migrations.AlterField(
            model_name='proveedorsolicitud',
            name='nit_cedula',
            field=models.CharField(db_column='Nitcedula', max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedorsolicitud',
            name='nombre_empresa',
            field=models.CharField(db_column='NombreEmpresa', max_length=255),
        ),
    ]
