# Generated by Django 5.1.1 on 2025-11-27 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_productospersonalizados_options_carrito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pagina_rastreo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='producto_personalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productospersonalizados'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='paypal_order_id',
            field=models.CharField(blank=True, help_text='ID de la orden de PayPal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='paypal_payer_email',
            field=models.EmailField(blank=True, help_text='Email del pagador en PayPal', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='paypal_payer_name',
            field=models.CharField(blank=True, help_text='Nombre del pagador en PayPal', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, help_text='ID de la transacción de PayPal', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='producto_personalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productospersonalizados'),
        ),
        migrations.AddField(
            model_name='productospersonalizados',
            name='color',
            field=models.CharField(blank=True, db_column='color', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productospersonalizados',
            name='estampados',
            field=models.ManyToManyField(blank=True, related_name='personalizados', through='api.ProductosPersonalizadosHasEstampado', to='api.estampado'),
        ),
        migrations.AddField(
            model_name='productospersonalizados',
            name='productos_idProductos',
            field=models.ForeignKey(db_column='productos_idProductos', default=1, on_delete=django.db.models.deletion.CASCADE, to='api.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productospersonalizados',
            name='talla',
            field=models.CharField(blank=True, db_column='talla', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productospersonalizados',
            name='telaid',
            field=models.ForeignKey(blank=True, db_column='telaid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tela'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(default='Transferencia', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.producto'),
        ),
        migrations.AlterField(
            model_name='productospersonalizados',
            name='urlEspadarl',
            field=models.CharField(blank=True, db_column='urlEspadarl', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productospersonalizados',
            name='urlFrontal',
            field=models.CharField(blank=True, db_column='urlFrontal', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productospersonalizados',
            name='urlMangaDerecha',
            field=models.CharField(blank=True, db_column='urlMangaDerecha', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productospersonalizados',
            name='urlMangaIzquierda',
            field=models.CharField(blank=True, db_column='urlMangaIzquierda', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.estadopedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='transportadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transportadora'),
        ),
    ]
