# Generated by Django 5.2.2 on 2025-08-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_proveedorsolicitud_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedorsolicitud',
            name='id_solicitud',
            field=models.AutoField(db_column='id_solicitud', primary_key=True, serialize=False),
        ),
    ]
