# Generated by Django 5.2.2 on 2025-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_proveedorsolicitud_id_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorsolicitud',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado')], db_column='Estado', default='Pendiente', max_length=20),
        ),
    ]
