# Generated by Django 5.2.2 on 2025-08-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_proveedorsolicitud_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedorsolicitud',
            name='usuario',
        ),
    ]
